version: "3"

volumes:
  node_modules:
  dist:

services:

  client_dev:
    build:
      context: .
      dockerfile: ./docker/client_dev
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - dist:/home/node/app/dist
    ports:
      - "8080:8080"
    command: ["npm", "run", "dev:client"]

  dev_server:
    image: node:10.2
    user: node
    working_dir: /home/node/app
    depends_on:
      - client_dev
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev:server"]

  nginx:
    image: nginx:1.14
    depends_on:
      - dev_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/ssl:/etc/ssl
      - dist:/usr/share/nginx/html/dist
